"""empty message

Revision ID: 21205c8072a3
Revises: 
Create Date: 2018-04-08 15:11:08.002222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21205c8072a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telephone', sa.String(length=13), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('intention', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abroad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('age', sa.String(length=16), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('school', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=20), nullable=True),
    sa.Column('TOELF', sa.Integer(), nullable=True),
    sa.Column('IELTS', sa.Integer(), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('others', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=20), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('age', sa.String(length=16), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('company', sa.String(length=20), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('others', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('depart', sa.String(length=16), nullable=True),
    sa.Column('age', sa.String(length=16), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('major', sa.String(length=20), nullable=True),
    sa.Column('grades', sa.Integer(), nullable=True),
    sa.Column('others', sa.Text(), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('no', sa.String(length=16), nullable=False),
    sa.Column('school', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('age', sa.String(length=16), nullable=True),
    sa.Column('major', sa.String(length=16), nullable=True),
    sa.Column('depart', sa.String(length=16), nullable=True),
    sa.Column('term', sa.String(length=16), nullable=True),
    sa.Column('others', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('no', sa.String(length=16), nullable=False),
    sa.Column('school', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('willings', sa.Text(), nullable=True),
    sa.Column('major_in', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tea')
    op.drop_table('stu')
    op.drop_table('questions')
    op.drop_table('post')
    op.drop_table('job')
    op.drop_table('follow')
    op.drop_table('abroad')
    op.drop_table('user')
    # ### end Alembic commands ###
