"""empty message

Revision ID: b81fbfc76498
Revises: ebe35d32f50f
Create Date: 2018-05-27 11:13:59.516614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81fbfc76498'
down_revision = 'ebe35d32f50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abroad', sa.Column('hobby', sa.Text(), nullable=True))
    op.add_column('abroad', sa.Column('school_life', sa.Text(), nullable=True))
    op.add_column('abroad', sa.Column('self_evaluation', sa.Text(), nullable=True))
    op.add_column('job', sa.Column('hobby', sa.Text(), nullable=True))
    op.add_column('job', sa.Column('school_life', sa.Text(), nullable=True))
    op.add_column('job', sa.Column('self_evaluation', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('hobby', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('school_life', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('self_evaluation', sa.Text(), nullable=True))
    op.add_column('stu', sa.Column('hobby', sa.Text(), nullable=True))
    op.add_column('stu', sa.Column('school_life', sa.Text(), nullable=True))
    op.add_column('stu', sa.Column('self_evaluation', sa.Text(), nullable=True))
    op.add_column('tea', sa.Column('hobby', sa.Text(), nullable=True))
    op.add_column('tea', sa.Column('school_life', sa.Text(), nullable=True))
    op.add_column('tea', sa.Column('self_evaluation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tea', 'self_evaluation')
    op.drop_column('tea', 'school_life')
    op.drop_column('tea', 'hobby')
    op.drop_column('stu', 'self_evaluation')
    op.drop_column('stu', 'school_life')
    op.drop_column('stu', 'hobby')
    op.drop_column('post', 'self_evaluation')
    op.drop_column('post', 'school_life')
    op.drop_column('post', 'hobby')
    op.drop_column('job', 'self_evaluation')
    op.drop_column('job', 'school_life')
    op.drop_column('job', 'hobby')
    op.drop_column('abroad', 'self_evaluation')
    op.drop_column('abroad', 'school_life')
    op.drop_column('abroad', 'hobby')
    # ### end Alembic commands ###
